/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <fcntl.h>
#include <pthread.h>
#include <assert.h>
#include <string.h>
#include <SLES/OpenSLES.h>
#include <SLES/OpenSLES_Android.h>
#include "log.h"
#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
#include "libswscale/swscale.h"
#include "libavfilter/avfilter.h"
#include "libavutil/pixfmt.h"
#include "libswresample/swresample.h"
/* Header for class com_example_ffmpeg_FFmpegNative */

#ifndef _Included_com_example_ffmpeg_FFmpegNative
#define _Included_com_example_ffmpeg_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ffmpeg_FFmpegNative
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ffmpeg_FFmpegNative_urlprotocolinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ffmpeg_FFmpegNative
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ffmpeg_FFmpegNative_avformatinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ffmpeg_FFmpegNative
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ffmpeg_FFmpegNative_avcodecinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ffmpeg_FFmpegNative
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ffmpeg_FFmpegNative_avfilterinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ffmpeg_FFmpegNative
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ffmpeg_FFmpegNative_configurationinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ffmpeg_FFmpegNative
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ffmpeg_FFmpegNative_test
  (JNIEnv *, jclass, jclass);

JNIEXPORT jint JNICALL Java_com_example_ffmpeg_FFmpegNative_init
  (JNIEnv *, jclass, jstring);

JNIEXPORT jintArray JNICALL Java_com_example_ffmpeg_FFmpegNative_getVideoSize(JNIEnv *env, jobject obj);

JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegNative_setSurface(JNIEnv *env, jobject obj, jobject surface);

JNIEXPORT jint JNICALL Java_com_example_ffmpeg_FFmpegNative_setup(JNIEnv *env, jobject obj, jint jwidth, jint jheight);

void finish(JNIEnv *env);

void* decodeAndRender(void *data);

JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegNative_play(JNIEnv *env, jobject obj);

JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegNative_stop(JNIEnv *env, jobject obj);

int seek_frame(int tsms);

JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegNative_seekAt(JNIEnv *env, jobject obj, jint secs);

JNIEXPORT jstring JNICALL Java_com_example_ffmpeg_FFmpegNative_getMusicInfo(JNIEnv *env, jobject obj, jstring filename);

JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegNative_playMusic(JNIEnv *env, jobject obj, jstring filename);

JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegNative_release(JNIEnv *env, jobject obj);

JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegNative_pause(JNIEnv *env, jobject obj);

JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegNative_resume(JNIEnv *env, jobject obj);

JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegNative_initSL(JNIEnv *env, jobject obj);

JNIEXPORT jint JNICALL Java_com_example_ffmpeg_FFmpegNative_findDecoder(JNIEnv *env, jobject obj, jint codecID);

#ifdef __cplusplus
}
#endif
#endif
